# Site settings
timezone: DE
title: subdiff
tagline: subtract the bullshit, differentiate what's left
email: subdiff@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mathematician by choice, programmer by opportunity
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.subdiff.de" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "Roman Gilg"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme_settings:
  # Color for sidebar bar, links, etc
  highlight_color: "#bf443d"
  # Social media links, leave blank to ignore
  social: 
    github: subdiff
    twitter: subdiff
    facebook:
    gplus: 106466492800351778880
    # dribble:
    pinterest:

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: subdiff

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink: pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed

gems:
  - jekyll-paginate
